In [2]:
import numpy as np

In [3]:
np.random.random((3,3))

array([[0.72987601, 0.8670032 , 0.15058174],
       [0.04234036, 0.1452203 , 0.22200787],
       [0.38374915, 0.79994031, 0.62403727]])

In [4]:
np.random.randint(0,11,(5,5))

array([[ 8,  2,  4,  4,  9],
       [ 6,  0,  6, 10,  3],
       [ 8,  8,  0,  3,  3],
       [ 3,  8,  8,  0,  0],
       [ 1,  8, 10,  7,  0]], dtype=int32)

In [5]:
mat1 = np.ones((3,4))
print(mat1)
print("="*20)
mat2 = np.zeros((5,3))
print(mat2)
np.savez('np_file.npz', cat = mat1, dog = mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
====================
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [6]:
with np.load('np_file.npz') as file:
    mat1 = file['cat']
    mat2 = file['dog']
 
print(mat1)
print("="*20)
print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
====================
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [15]:
m1 = np.array([[1, 2, 3],
               [1, 1, 1]])

m2 = np.array([[7, 8, 9],
               [0, 0, 0]])

newmat = np.hstack((m1,m2))
newmat

array([[1, 2, 3, 7, 8, 9],
       [1, 1, 1, 0, 0, 0]])

In [14]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,4,6,8,9])
np.isclose(v1,v2, atol=2)

array([ True,  True, False, False, False])

In [17]:
v = np.array([1,3,5,4,7])
c = 2
sum = v +c
print(sum)

[3 5 7 6 9]

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\YoussefMohamed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\YoussefMohamed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\YoussefMohamed\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\YoussefMohamed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\YoussefMohamed\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [9]:
s = pd.Series([1,2,3,4,5], index = ['a','c','e','f','g'])
s

a    1
c    2
e    3
f    4
g    5
dtype: int64

In [12]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
 
data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)
type(df)

pandas.DataFrame

In [15]:
cols = ['col1','col2','col3']
df.columns = cols
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [23]:
df['col1'] = df['col1'].astype("category")
df['col2'] = df['col2'].astype("category")

df.dtypes

col1    category
col2    category
col3         str
dtype: object

In [24]:
df.describe(include="category")

        col1  col2
count      4     4
unique     4     3
top        1   444
freq       1     2

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      category
 1   col2    4 non-null      category
 2   col3    4 non-null      str
dtypes: category(2), str(1)
memory usage: 240.0 bytes

In [26]:
df['col1'].apply(lambda x :x*2)

0    2
1    4
2    6
3    8
Name: col1, dtype: category
Categories (4, int64): [2, 4, 6, 8]

In [27]:
x = df.iloc[:,0:2]
x

  col1 col2
0    1  444
1    2  555
2    3  666
3    4  444

In [28]:
df.drop(['col1','col2'],axis=1)

  col3
0  abc
1  def
2  ghi
3  xyz